phone check in login removed
elisntdead/FYPC-backend pull request #1
Opened 2023-01-31 11:21 UTC by elisntdead

2023-02-01 14:19 UTC, SergeiGD requested changes
Отельный css файл для страниц обработчиков 404 403

2023-02-01 14:19 UTC, SergeiGD commented on FYPC/templates/403.html
> +    <h1 style="font-size: 2em;"><i class="fa-solid fa-lock fa-xl" style="margin-right: 10px;"></i>Access Denied</h1>
Стили повторяются на странице для 404 + потом в будущем таких страниц может стать еще больше, так что выносим в отдельный css файл

2023-02-02 05:03 UTC, elisntdead commented on FYPC/templates/403.html
> +    <h1 style="font-size: 2em;"><i class="fa-solid fa-lock fa-xl" style="margin-right: 10px;"></i>Access Denied</h1>
закинул стили в основной css

2023-02-05 04:23 UTC, SergeiGD commented on FYPC/base/views.py
> +  similar_products = similar_products.annotate(num_matching_tags=Count('tags', filter=Q(tags__in=product.tags.all())))
зачем дважды filter?

2023-02-12 05:04 UTC, merged